### ISSUE TITLE
.download()

### ISSUE THREAD

**Issue by kaaninel** [markmarijnissen/cordova-file-cache#5]
Uncaught (in promise) ["http://wallpapers.wallhaven.cc/wallpapers/full/wallhaven-95691.jpg"]

**Comment by markmarijnissen** [comment]
I have no idea what you mean.

Can you make a screenshot of the error?
Can you tell me the steps to reproduce the issue?
Can you create a jsfiddle of gist in which I can see the issue?

**Comment by nashfive** [comment]
Hi,
I ran into that error as well with the sample code. It appears that the cordova-plugin-file-transfer is not optional when you want to download stuff. It's not very clear in the README, so I didn't install it, hence the uncaught exception bubbling from the promise because of (apparently) the FileTransfer object. 
I installed the cordova-plugin-file-transfer and it runs fine now.
